### ISSUE TITLE
ValueError: Index out of range using input dim 0; input has only 0 dims for 'coarse_decoder_8/while/strided_slice' (op: 'StridedSlice') with input shapes: [], [1], [1], [1].

### ISSUE THREAD

**Issue by shr-2311** [phineasng/MrRNN#2]
This s the error i am getting while trying to run the train.py code. i tried with tensorflow 0.10 and 0.12.
Kindly help me with this issue.

0.12.1
Traceback (most recent call last):

  File "<ipython-input-17-fc19efdeaa45>", line 1, in <module>
    runfile('C:/Project2016/Shreya/ICON-2017/DialogueSystem/MrRNN-master/train.py', wdir='C:/Project2016/Shreya/ICON-2017/DialogueSystem/MrRNN-master')

  File "C:\Program Files\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Program Files\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Project2016/Shreya/ICON-2017/DialogueSystem/MrRNN-master/train.py", line 54, in <module>
    model = MRRNN(config)

  File "C:\Project2016\Shreya\ICON-2017\DialogueSystem\MrRNN-master\mrrnn.py", line 94, in __init__
    self._build_graph()

  File "C:\Project2016\Shreya\ICON-2017\DialogueSystem\MrRNN-master\mrrnn.py", line 255, in _build_graph
    self.coarse_prediction = self._create_coarse_decoder()

  File "C:\Project2016\Shreya\ICON-2017\DialogueSystem\MrRNN-master\mrrnn.py", line 216, in _create_coarse_decoder
    tf.TensorShape([self.coarse_decoder_hid_size])])

  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2636, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)

  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2469, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)

  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2405, in _BuildLoop
    c = ops.convert_to_tensor(pred(*packed_vars))

  File "C:\Project2016\Shreya\ICON-2017\DialogueSystem\MrRNN-master\mrrnn.py", line 177, in decoder_coarse_condition
    return it[0] < self.output_coarse_length[0]

  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 436, in _SliceHelper
    name=name)

  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 590, in strided_slice
    shrink_axis_mask=shrink_axis_mask)

  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3503, in strided_slice
    shrink_axis_mask=shrink_axis_mask, name=name)

  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 759, in apply_op
    op_def=op_def)

  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2242, in create_op
    set_shapes_for_outputs(ret)

  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1617, in set_shapes_for_outputs
    shapes = shape_func(op)

  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1568, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)

  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)

  File "C:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)

ValueError: Index out of range using input dim 0; input has only 0 dims for 'coarse_decoder_6/while/strided_slice' (op: 'StridedSlice') with input shapes: [], [1], [1], [1].

**Comment by phineasng** [comment]
hey @shr-2311, unfortunately I am not planning to maintain this code. I am keeping it public just as a rough reference. If I have time in future I might look into your issue, but right now is definitely not on my priority list. Sorry :/ .

However, @bamattsson has an implementation as well at https://github.com/bamattsson/MrRNN . I think he recently played with it and didn't have any issue, so it may work for you out-of-the-box. Have a look! :)

**Comment by shr-2311** [comment]
Thanks so much. I'll have a look at that code as well.

**Comment by kells94** [comment]
hey @shr-2311 , were you able to solve this problem ?
I checked out the bamtasson one but it didnt have a generate function , which is what I wanted to run

any help would be appreciated
