### ISSUE TITLE
which version of tensorflow for this project?

### ISSUE THREAD

**Issue by SeekPoint** [phineasng/MrRNN#4]

**Comment by phineasng** [comment]
hey @loveJasmine, not 100% sure, but I think it was either v0.10 or v0.11

**Comment by SeekPoint** [comment]
works well on Mac(no gpu) , tf0.11

but failed on linux with GPU, tf0.11


$python train.py
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
^@^@^@^@^@^@^@^@^@^@^@Traceback (most recent call last):
  File "train.py", line 54, in <module>
    model = MRRNN(config)
  File "/MrRNN/MrRNN/mrrnn.py", line 93, in __init__
    self._build_graph()
  File "/MrRNN/MrRNN/mrrnn.py", line 253, in _build_graph
    self.coarse_prediction = self._create_coarse_decoder()
  File "/MrRNN/MrRNN/mrrnn.py", line 214, in _create_coarse_decoder

▽
    tf.TensorShape([self.coarse_decoder_hid_size])])
  File "/vetf0.11py2/venv/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2518, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/vetf0.11py2/venv/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2356, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/vetf0.11py2/venv/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2292, in _BuildLoop
    c = ops.convert_to_tensor(pred(*packed_vars))
  File "/MrRNN/MrRNN/mrrnn.py", line 175, in decoder_coarse_condition
    return it[0] < self.output_coarse_length[0]
  File "/vetf0.11py2/venv/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 383, in _SliceHelper
    name=name)
  File "/vetf0.11py2/venv/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 537, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/vetf0.11py2/venv/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2750, in strided_slice
    shrink_axis_mask=shrink_axis_mask, name=name)
  File "/vetf0.11py2/venv/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/vetf0.11py2/venv/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2382, in create_op
    set_shapes_for_outputs(ret)
  File "/vetf0.11py2/venv/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1783, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/vetf0.11py2/venv/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1645, in _DelegateStridedSliceShape
    return common_shapes.call_cpp_shape_fn(op, input_tensors_needed=[1, 2, 3])
  File "/vetf0.11py2/venv/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 596, in call_cpp_shape_fn
    raise ValueError(err.message)
ValueError: Index out of range using input dim 0; input has only 0 dims
